linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - stylecheck
    - unconvert
    - unused
    - varcheck
    - dogsled
    - dupl
    - funlen
    - gocognit
    - godox
    - prealloc
    - scopelint
    - typecheck
    - unparam
    - whitespace
