name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Download golangci-lint
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sudo sh -s -- -b /usr/local/bin v1.26.0
    - name: Download
      run: make download
    - name: Lint
      run: make lint
    - name: Test
      run: make test
    - name: Benchmark
      run: make benchmark
    - name: Build
      run: make build
